### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by mrbrutti** [mongomapper/mongomapper#655]
**Linux:** Ubuntu 17.04
**Ruby version:**  2.3.1
**mongodb:** 3.2.11

Any idea what could be going wrong ? Should I update/downgrade something ? 

Cheers

Matias

```
2.3.1 :002 > MongoMapper.connection = ::Mongo::Connection.new('localhost',27017)
ArgumentError: wrong number of arguments (given 2, expected 1)
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bson-1.12.5/lib/bson/bson_c.rb:24:in `deserialize'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/bson-1.12.5/lib/bson/bson_c.rb:24:in `deserialize'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/networking.rb:238:in `read_documents'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/networking.rb:184:in `receive'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/networking.rb:146:in `receive_message'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/cursor.rb:551:in `block in send_initial_query'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:55:in `block in instrument'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:20:in `instrument'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:54:in `instrument'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/cursor.rb:547:in `send_initial_query'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/cursor.rb:532:in `refresh'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/cursor.rb:139:in `next'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/db.rb:607:in `command'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:542:in `block in check_is_master'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:541:in `check_is_master'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:395:in `connect'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:656:in `setup'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/mongo_client.rb:179:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.1/gems/mongo-1.12.5/lib/mongo/legacy.rb:52:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /usr/local/rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by pavelvasev** [comment]
I had the same problem. Investigation showed that my system for whatever reason used older version of bson_ext gem. And bundle install/update for some reason didn't load latest version.
Btw there is API change in `deserialize` method in that old and the latest version of bson_ext.

Had "fixed" this by manually specifying version of gem in Gemfile:
```
gem 'bson_ext', ">=1.12.5"
```

**Comment by smtlaissezfaire** [comment]
Guessing this is out of date. Going to close. 

With mongomapper 0.15+, you can use: 

`MongoMapper.connection = Mongo::Client.new(['127.0.0.1:27017'])`

Thanks for the report!
