### ISSUE TITLE
default option for key doesn't work since #678

### ISSUE THREAD

**Issue by mtsmfm** [mongomapper/mongomapper#679]
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'pry-byebug'
  gem 'mongo_mapper', git: 'https://github.com/mongomapper/mongomapper', ref: ENV.fetch('MM_REF')
end

class Foo
  include MongoMapper::Document
  key :foo, default: 0
end

MongoMapper.setup({'development' => {'uri' => 'mongodb://mongo/test'}}, 'development', logger: Logger.new(File::NULL))

Foo.new

puts 'OK'

__END__
$ MM_REF=v0.15.3 ruby memo.rb
OK

$ MM_REF=3123afb ruby memo.rb
Traceback (most recent call last):
        13: from memo.rb:17:in `<main>'
        12: from memo.rb:17:in `new'
        11: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/partial_updates.rb:18:in `initialize'
        10: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/callbacks.rb:8:in `initialize'
         9: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/embedded_callbacks.rb:78:in `run_callbacks'
         8: from /usr/local/bundle/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
         7: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/callbacks.rb:8:in `block in initialize'
         6: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/sci.rb:77:in `initialize'
         5: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/keys.rb:267:in `initialize'
         4: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/keys.rb:466:in `initialize_default_values'
         3: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/keys.rb:466:in `each'
         2: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/keys.rb:468:in `block in initialize_default_values'
         1: from /vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/plugins/keys/key.rb:96:in `default_value'
/vendor/bundle/2.6.6/ruby/2.6.0/bundler/gems/mongomapper-3123afb71699/lib/mongo_mapper/extensions/object.rb:17:in `to_mongo': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

Is this intentional?

**Comment by smtlaissezfaire** [comment]
Definitely a regression.  Will post a fix in a minute!

Thanks for testing!
